function [fitresult, gof] = functionFourier4(xSin, ySin)
%CREATEFIT(XSIN,YSIN)
%  Create a fit.
%
%  Data for 'fit1' fit:
%      X Input : xSin
%      Y Output: ySin
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Jan-2018 09:47:27


%% Fit: 'fit1'.
[xData, yData] = prepareCurveData( xSin, ySin );

% Set up fittype and options.
ft = fittype( 'fourier4' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0 0 0 0 0 0 0 0 0 2.00391389432485];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'fit1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'ySin vs. xSin', 'fit1', 'Location', 'NorthEast' );
% % Label axes
% xlabel xSin
% ylabel ySin
% grid on


